#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_Basit_Corporation.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Albbasitcorporation")]
	public partial class investerbqayaDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertinvesterbqayaamount(investerbqayaamount instance);
    partial void Updateinvesterbqayaamount(investerbqayaamount instance);
    partial void Deleteinvesterbqayaamount(investerbqayaamount instance);
    #endregion
		
		public investerbqayaDataClassesDataContext() : 
				base(global::Al_Basit_Corporation.Properties.Settings.Default.AlbbasitcorporationConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public investerbqayaDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public investerbqayaDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public investerbqayaDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public investerbqayaDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<investerbqayaamount> investerbqayaamounts
		{
			get
			{
				return this.GetTable<investerbqayaamount>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.investerbqayaamount")]
	public partial class investerbqayaamount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nameinvester;
		
		private string _bqayaamount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameinvesterChanging(string value);
    partial void OnnameinvesterChanged();
    partial void OnbqayaamountChanging(string value);
    partial void OnbqayaamountChanged();
    #endregion
		
		public investerbqayaamount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameinvester", DbType="NVarChar(200)")]
		public string nameinvester
		{
			get
			{
				return this._nameinvester;
			}
			set
			{
				if ((this._nameinvester != value))
				{
					this.OnnameinvesterChanging(value);
					this.SendPropertyChanging();
					this._nameinvester = value;
					this.SendPropertyChanged("nameinvester");
					this.OnnameinvesterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bqayaamount", DbType="NVarChar(200)")]
		public string bqayaamount
		{
			get
			{
				return this._bqayaamount;
			}
			set
			{
				if ((this._bqayaamount != value))
				{
					this.OnbqayaamountChanging(value);
					this.SendPropertyChanging();
					this._bqayaamount = value;
					this.SendPropertyChanged("bqayaamount");
					this.OnbqayaamountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
